### PR TITLE
Gracefully handle postgres error 22P02

### LINKED ISSUE #135: non-integer ID input results in SQL parse 500 response
as mentioned by akshay on slack:

```
curl -X DELETE \
  http://localhost:8383/v1/field-keys/324fdsd \
  -H 'Authorization: Bearer <cut>'
```

results in 

```
{ error: invalid input syntax for integer: "324fdsd"
    at Connection.parseE (F:\Akshay\wGit\central-backend\node_modules\pg\lib\connection.js:545:11)
    at Connection.parseMessage (F:\Akshay\wGit\central-backend\node_modules\pg\lib\connection.js:370:19)
    at Socket.<anonymous> (F:\Akshay\wGit\central-backend\node_modules\pg\lib\connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 97,
  severity: 'ERROR',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '106',
  routine: 'pg_atoi' }
```

this should be solvable with an addition for `22P02` to the sql error translation layer.

### PR DESCRIPTION
**Pull request by akshay-ap**
Closes #135 
Request:
```
curl -X DELETE \
  http://localhost:8383/v1/field-keys/6aaa \
  -H 'Authorization: Bearer <token>' \
```
Resoponse produced:

```
{
    "message": "Invalid data-type of '6aaa' in url. Expected data-type (integer)",
    "code": 400,
    "details": {
        "value": "6aaa",
        "expected": "integer"
    }
}
```

### CODE REVIEW

**Comment by clint-tseng** [comment]
As mentioned on Slack (with some additions), I'm hoping for:

1. Some cleanup of the whitespace to match the rest of the code.
2. Modification of the commit message to match the format in the contribution guide.
3. A minor `.x` code assignment to the new `Problem` type.
4. The addition of at least one integration test to exercise the new failure case.

**Comment by clint-tseng** [comment]
Still a whitespace problem in problem.js, and the commit message is close but still not correct, and I'm still looking for an integration test that shows the new error being returned.

**Comment by akshay-ap** [comment]
When I run `make test-integration` (on the latest code) I get following error:
```
$ make test-integration
node node_modules/mocha/bin/mocha --recursive test/integration


  1) "before all" hook

  0 passing (2s)
  1 failing

  1) "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.


```
Am I missing something?

**Comment by clint-tseng** [comment]
Hm. Try `npm install` just to be sure?

**Pull request closed without merging**
